/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasosGreenpacRouteImport } from './routes/casos/greenpac'
import { Route as CasosPatagoniaVesselsRouteImport } from './routes/casos/patagonia-vessels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosGreenpacRoute = CasosGreenpacRouteImport.update({
  id: '/casos/greenpac',
  path: '/casos/greenpac',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosPatagoniaVesselsRoute = CasosPatagoniaVesselsRouteImport.update({
  id: '/casos/patagonia-vessels',
  path: '/casos/patagonia-vessels',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casos/greenpac': typeof CasosGreenpacRoute
  '/casos/patagonia-vessels': typeof CasosPatagoniaVesselsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casos/greenpac': typeof CasosGreenpacRoute
  '/casos/patagonia-vessels': typeof CasosPatagoniaVesselsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casos/greenpac': typeof CasosGreenpacRoute
  '/casos/patagonia-vessels': typeof CasosPatagoniaVesselsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/casos/greenpac' | '/casos/patagonia-vessels'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/casos/greenpac' | '/casos/patagonia-vessels'
  id: '__root__' | '/' | '/casos/greenpac' | '/casos/patagonia-vessels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasosGreenpacRoute: typeof CasosGreenpacRoute
  CasosPatagoniaVesselsRoute: typeof CasosPatagoniaVesselsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/greenpac': {
      id: '/casos/greenpac'
      path: '/casos/greenpac'
      fullPath: '/casos/greenpac'
      preLoaderRoute: typeof CasosGreenpacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/patagonia-vessels': {
      id: '/casos/patagonia-vessels'
      path: '/casos/patagonia-vessels'
      fullPath: '/casos/patagonia-vessels'
      preLoaderRoute: typeof CasosPatagoniaVesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasosGreenpacRoute: CasosGreenpacRoute,
  CasosPatagoniaVesselsRoute: CasosPatagoniaVesselsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
